name: mule-sap-supply-chain-purchase-order-sapi CI
on: 
  push:
    branches: [ master ]
  pull_request:
   branches: [master ]
jobs:
  build:
    runs-on: ubuntu-latest

 

    steps:
        - uses: actions/checkout@v2
        - name: Create maven settings.xml
          uses: whelk-io/maven-settings-xml-action@v5
          with:
            servers: '[{"id": "MuleRepository", "username": "${{ secrets.MULE_ENT_USERNAME_NEXUS }}", "password": "${{ secrets.MULE_ENT_PASSWORD_NEXUS }}"},{"id": "anypoint-exchange", "username": "${{ secrets.ANYPOINT_PLATFORM_USER }}", "password": "${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}" }]'
            repositories: '[{"id": "MuleRepository", "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/"},{"id": "local-repo", "url": "file:///${project.basedir}/local-repo"},{"id": "anypoint-exchange", "url": "https://maven.anypoint.mulesoft.com/api/v2/maven"},{"id": "mulesoft-releases", "url": "https://repository.mulesoft.org/releases/"},{"id": "mule-public", "url": "https://repository.mulesoft.org/nexus/content/repositories/public"}]' 
        - run: |
            cat ~/.m2/settings.xml
        - name: Set up JDK 1.8 version
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
            path: ~/.m2/repository
            settings-path: ${{ github.workspace }} # location for the settings.xml file

 

        - name: Build and cloudhub deployment
          run: mvn clean package deploy -DmuleDeploy -Dmule.env=${{secrets.ENV}} -Dusername=${{secrets.ANYPOINT_PLATFORM_USER}} -Dpassword=${{secrets.ANYPOINT_PLATFORM_PASSWORD}} 
